nbgallery/nbgallery

app/assets/stylesheets/gallery.css
public/integration/gallery-notebook.js

Two small typos: one in the css that was targeting a class that does not exist, one in the text on a page.

Fix notebok -> notebook

---

app/assets/javascripts/application.js
app/assets/javascripts/beta.js
app/assets/javascripts/gallery.js.erb
app/assets/stylesheets/application.scss
app/assets/stylesheets/beta.css
app/controllers/application_controller.rb
app/controllers/static_pages_controller.rb
app/views/application/_beta_notebooks_table.slim
app/views/application/_nb_stats.slim
app/views/application/_notebooks.slim
app/views/application/_table_nb_description.slim
app/views/application/_table_nb_title.slim
app/views/layouts/beta_layout.slim
app/views/notebooks/index.slim
app/views/static_pages/beta_home_notebooks.slim
app/views/static_pages/beta_notebook.slim
app/views/static_pages/home.slim
app/views/users/summary.slim
config/initializers/gallery.rb
config/routes.rb
config/settings.yml
vendor/assets/javascripts/jquery.sparkline.js
vendor/assets/stylesheets/loading.css

Merge beta branch into master

---

app/assets/javascripts/gallery.js.erb
app/assets/stylesheets/modals.scss
app/assets/stylesheets/styles.scss

Removed box shadow of modal close buttons and changed styling of UUID modal button to match rest of application

Removed box shadow of modal close buttons and changed styling of UUID modal button to match rest of application

---

app/views/layouts/layout.slim

This will display who is logged in with the dropdown menu in the header for users

Show logged in user, using the user_name variable.

---

app/assets/stylesheets/styles.scss
app/views/application/_notebook_metadata.slim
app/views/application/_tags_edit.slim
app/views/application/_tags_view.slim
app/views/notebooks/_notebook_info_jumbotron.slim

Accessibility-5: Added some pronounced hover and focus affects on the jumbotron elements and fixed a tag bug

Accessibility-5: Added some pronounced hover and focus affects on the jumbotron elements and fixed a tag bug

---

app/assets/stylesheets/styles.scss
app/views/application/not_modern_browser.slim
app/views/layouts/beta_layout.slim
app/views/layouts/layout.slim

Cleaned up View when on Compatibility mode on IE or in general using any unsupported Browser/Version

Cleaned up View when on Compatibility mode on IE or in general using any unsupported Browser/Version

---

app/controllers/static_pages_controller.rb
app/views/static_pages/robots.erb
config/routes.rb

Techdebt-cleanup-2: Removed all trace elements of the feed and home_feed

Techdebt-cleanup-2: Removed all trace elements of the feed and home_feed

---

app/assets/stylesheets/modals.scss
app/assets/stylesheets/styles.scss
app/assets/stylesheets/variables.scss
app/views/application/_tags_view.slim
app/views/notebooks/_notebook_info_jumbotron.slim
app/views/notebooks/_notebook_jumbotron_title.slim
app/views/reviews/show.slim

Accessibility 11: Fixed a handful of contrast and font-size issues

Accessibility 11: Fixed a handful of contrast and font-size issues

---

app/assets/javascripts/gallery.js.erb
app/assets/stylesheets/styles.scss
app/views/layouts/beta_layout.slim
app/views/layouts/layout.slim
app/views/static_pages/home.slim
app/views/static_pages/video.slim
config/settings.yml

More of a series of tech debt fixes, but for the end goal of helping accessibility
Has been tested

Accessibility-10: Removed forced tab order and other hacks that caused users to jump to top of page after a page was done loading.

---

app/controllers/notebooks_controller.rb
app/controllers/users_controller.rb

Some minor improvements to json endpoints requested by API users

API metadata

---

app/assets/stylesheets/styles.scss
app/controllers/application_controller.rb
app/controllers/notebooks_controller.rb
app/views/application/_reviews.slim

Catchup-3: Fixed reviews for private pages and added browser titles for the user's review page.
Note - Have tested

Catchup-3: Fixed reviews for private pages and added browser titles for the user's review page

---

app/views/application/_html_head.slim

Hotfix-2: Made it so users without user preferences don't receive an error on every page they visit

Hotfix-2: Made it so users without user preferences don't receive an error on every page they visit

---

app/views/notebooks/_notebook_info_jumbotron.slim

Disables Subs and Stars for Anonymous users

Disables Subs and Stars for Anonymous users

---

app/assets/javascripts/gallery.js.erb
app/assets/stylesheets/styles.scss
app/models/notebook.rb
app/views/application/_notebooks.slim

-Fixed an alert issue where it was appearing twice on notebook listing pages
-Fixed a coloring issue for ultra dark theme
-Fixed an z-alignment issue for ultra dark theme
-Cleaned up dark theme a tid bit for the search container
-Fix for snippetInfo for certain types of returns (weird irregular issue)
-Got recommended dropdown elements loading properly again.

Catchup-4: Catchup

---

app/views/application/_notebook_listings.slim
app/views/application/_notebook_run.slim
app/views/application/_notebook_tile.slim
app/views/change_requests/compare.slim
app/views/notebooks/_notebook_info_jumbotron.slim

This is going to cause conflicts with https://github.com/nbgallery/nbgallery/pull/140 so I will refactor this if that branch gets merged in first

Move Run In Jupyter button into partial

---

app/assets/javascripts/gallery.js.erb

Fixing a bug where the first upload notebook modal didn't close properly

Fix issue with upload notebook modal

---

app/assets/javascripts/run_in_jupyter.js.erb
app/assets/stylesheets/styles.scss
app/controllers/application_controller.rb

Cleaning up error handling for Run in Jupyter button

---

app/views/groups/show.slim
app/views/tags/show.slim
app/views/users/show.slim

Hide the subscribe icon for non-authenticated users

---

app/assets/javascripts/notebook_actions.js.erb
app/controllers/notebooks_controller.rb
app/views/notebooks/_notebook_info_jumbotron.slim

Add success flash message for Private/Public

---

app/views/groups/index.slim
app/views/layouts/beta_layout.slim
app/views/layouts/layout.slim
app/views/modals/_new_group.slim
app/views/static_pages/layout_dropdown.slim
app/views/users/groups.slim

Closes #211 
closes #213 
closes #214 
Related to #216 
Related to #215

Group creation bugs

---

app/assets/javascripts/login.js

It does not change the behavior if they end up at the login page from redirect because that may break things in other devise plugins
closes #224

This resolves the issue for AJAX sign-ins.

---

app/views/notebooks/_notebook_info_jumbotron.slim

Hides menu options that would result in a login prompt from users

---

docs/configuration.md
script/bulk_import.rb

A partial solution for bulk loading of notebooks

Notebook seeding from the command line

---

app/views/groups/show.slim
app/views/modals/_manage_group.slim

First cut of documenting the group permission levels in the UI

---

app/views/change_requests/index.slim

Fix owner on change request screen

---

app/controllers/application_controller.rb
app/controllers/notebooks_controller.rb
app/models/user.rb
app/views/notebooks/_notebook_info_jumbotron.slim

Permissions Fix: Removed owner actions from users with editor permissions

---

app/assets/javascripts/groups.js
app/controllers/groups_controller.rb
app/views/groups/show.slim

Changes the tool tip to "Edit Group" Because it does more than menbership
Adds flash message
triggers location.reload on success

Closes #239

---

app/assets/javascripts/notebook_actions.js.erb
app/controllers/notebooks_controller.rb

Properly handle notebook deletion AJAX and prevent 500 error

---

Gemfile
Gemfile.lock

tested, and sdoc still works this way as well.

Gets rid of at least one vulnerable package)

---

docker-compose.yml
docs/docker.md

Documentation for using a fake SMTP server for development Closes #251

---

app/assets/stylesheets/styles.scss
app/controllers/users_controller.rb
app/models/user.rb
app/views/users/index.slim

Closes 122
Could use an accessibility check-over by @manfromjupyter because I haven't found a good document for "smart tables" for filtering records.

Added the ability to filter the "All Users" page used by admins

---

app/views/notebooks/_ownership_autocomplete.slim

Allow admins to change ownership to groups they are not part of

---

config/application.rb

Allow option to disable verification of SSL

---

app/assets/javascripts/notebook_actions.js.erb
app/controllers/change_requests_controller.rb

Change Request approvals, declining, and cancelling no longer hangs or returns server errors

---

app/views/application/_external_resources.slim

Closes #331 
Can confirm works on /notebooks/41-typsetting-equations.

GITHUB-331: made external resource open in new tab and alert accessibility users they are external links.

---

app/views/modals/_notebook_metric_details.slim

GITHUB-327: Properly sort Metric modal datatables now.

---

app/assets/javascripts/notebook_actions.js.erb

Corrected the id of the element for setting the title of the
change request dialog when submitting from Jupyter
Closes #302

Change Request Dialog Missing Title

---

app/assets/stylesheets/styles.scss
app/views/layouts/beta_layout.slim
app/views/layouts/layout.slim

GITHUB-203: Added more context to screenreader text for the home link so screenreader users know what they're clicking on/looking at

---

app/controllers/notebooks_controller.rb

Used a variation of the code from the readable megajoin
to allow sorting of the shared with me page.
Not the most elegant solution, but the readable mega join isn't designed to use the shares relationship.

Closes 317 - Sorting Shared with Me

---

app/assets/stylesheets/styles.scss
app/views/modals/_notebook_actions.slim

Tested ultra dark and dark theme, deleting external resources, and that a handful of other things were not suddenly broken

Minor Fixes: Touchups to the dark theme mostly

---

app/models/notebook.rb
app/models/user.rb

Delete Comments made by a user when they are deleted
Delete Comments made on a notebook when it is deleted
Closes #363
Closes #362

Cascade deleting comments

---

app/views/users/index.slim

Closes #332 
@manfromjupyter can critique/improve the UI facet if you want

Add "Reset" button to clear filters

---

app/models/group.rb
app/models/notebook.rb
app/models/user.rb

MERGE AFTER #368 
Partially addresses #353 
Tags are still a problem...Won't address tags until #360 is done.

Cascade delete subscription

---

app/views/modals/_notebook_actions.slim
app/views/notebooks/_notebook_deprecated_banner.slim

Fixes 404 error when the user who deprecated the notebook is deleted
Fixes 404 error when 1..n of the alternate notebooks are deleted
Closes #364 and fixes related bug

Deprecation render errors if alternate notebook or user are deleted

---

app/models/notebook.rb

Sets Creator and or Updator to Unknown in solr if the user has been deleted

---

app/assets/stylesheets/styles.scss

Make sure only the mobile or "Notebooks" menu appear, not both

---

app/assets/stylesheets/styles.scss

Fix accidental bolding of alert banner

---

app/assets/stylesheets/styles.scss
app/views/application/_html_head.slim

Didn't mean to put these in the same branch but oh well.
Fixes subscription and star icon for ultra dark and for ultra dark and grayscale theme fixed the modal issue where it was wrapping over the top of the page (worse for low vision users)
Closes #188 and #394

Coloring issue fix with subscription and star icon for ultra dark theme

---

app/assets/stylesheets/styles.scss
app/views/layouts/beta_layout.slim
app/views/layouts/layout.slim
config/environments/development.rb

Add "Upload" button to mobile menu

---

app/assets/stylesheets/styles.scss
app/views/admin/index.slim
app/views/layouts/beta_layout.slim
app/views/layouts/layout.slim
app/views/notebooks/_notebook_info_jumbotron.slim
app/views/notebooks/show.slim
app/views/static_pages/home.slim

Closes #365 
Made proper header, added navs, tablist for home page, and made notebook region so user knows to read it as read-only (no real buttons to click on). Tabbing by links, buttons will vary so feel like need to keep it consistent so they know.
Notebook region may need to be a type of article instead so the heading violations (two H1s side by side) are not seen a problem but not sure article really applies so just made it a generic region section with the label "Notebook content"

Landmarks: Added numerous ARIA landmarks for screenreaders as well as proper semantic html fixes

---

app/assets/javascripts/notebook_actions.js.erb
app/views/modals/_notebook_actions.slim

Deprecate Notebook Submit Form Button Fix

---

app/controllers/notebooks_controller.rb

Sets Updater and Creator to Unknown in metadata call

---

app/assets/javascripts/gallery.js.erb
app/assets/stylesheets/styles.scss
app/views/modals/_view_group.slim

Closes #403
Waiting for feedback on changes to the dialogs.

WIP: Empty group members

---

app/models/review.rb

Exclude clicks on deprecated notebooks when picking those for review

---

app/assets/javascripts/notebook_actions.js.erb
app/controllers/notebooks_controller.rb
app/views/modals/_notebook_actions.slim
app/views/notebook_mailer/feedback.html.slim
app/views/notebook_mailer/feedback.text.slim

Provide Feedback fix: Made it so fields are hidden when they should be

---

app/assets/javascripts/gallery.js.erb
app/assets/javascripts/notebook_actions.js.erb
app/assets/stylesheets/modals.scss
app/assets/stylesheets/styles.scss
app/controllers/change_requests_controller.rb
app/controllers/notebooks_controller.rb
app/controllers/revisions_controller.rb
app/models/user.rb
app/views/change_request_mailer/accept.html.slim
app/views/change_request_mailer/accept.text.slim
app/views/change_request_mailer/cancel.html.slim
app/views/change_request_mailer/cancel.text.slim
app/views/change_request_mailer/create.html.slim
app/views/change_request_mailer/create.text.slim
app/views/change_request_mailer/decline.html.slim
app/views/change_request_mailer/decline.text.slim
app/views/change_requests/all.slim
app/views/change_requests/index.slim
app/views/change_requests/show.slim
app/views/layouts/mailer.html.slim
app/views/modals/_notebook_actions.slim
app/views/notebooks/_notebook_jumbotron_title.slim
app/views/revisions/index.slim
config/routes.rb
db/migrate/20201207123432_add_commit_message_to_revisions.rb
db/migrate/20201210161324_add_commit_message_to_change_requests.rb

Reverts nbgallery/nbgallery#222

Revert "Commit messages"

---

app/assets/javascripts/gallery.js.erb
app/assets/stylesheets/styles.scss
app/controllers/application_controller.rb
app/views/application/_notebooks.slim
app/views/user_preferences/index.slim

Will close #339
Having a dev box issue so pushing what I have. Will finish the rest of it in a bit.

Enable option to enable private notebooks in notebook listings when user is admin

---

app/assets/javascripts/gallery.js.erb
app/controllers/notebooks_controller.rb
app/models/notebook.rb
app/views/application/_notebooks.slim

Change show_deprecated from being a 1 to true

---

app/assets/javascripts/gallery.js.erb
app/controllers/notebooks_controller.rb
app/models/notebook.rb
app/views/application/_notebooks.slim
app/views/application/_search_banner.slim

Related to #453 Saves the flags so you can change/refine your search terms without losing that you had toggled the filter.

Search preserve flags

---

app/controllers/application_controller.rb
app/controllers/groups_controller.rb
app/models/group.rb

Throw an error if users try to add a user who doesn't exist to a group

---

app/assets/javascripts/gallery.js.erb
app/assets/javascripts/groups.js
app/controllers/groups_controller.rb
app/controllers/notebooks_controller.rb
app/models/notebook.rb
app/views/application/_notebooks.slim

Group notebook listing params

---

app/controllers/admin_controller.rb
app/views/admin/index.slim
config/routes.rb

Includes a metadata.json file with notebook information
closes #468

Add ability to download a tgz of public notebooks

---

app/controllers/admin_controller.rb

Fix Export Metadata Owner name for Groups

---

app/views/subscription_mailer/daily_subscription_email.html.slim
app/views/subscription_mailer/daily_subscription_email.text.slim

Fix a casting error where an array was being used as a tag object

---

app/views/change_request_mailer/accept.html.slim
app/views/change_request_mailer/accept.text.slim
app/views/change_request_mailer/cancel.html.slim
app/views/change_request_mailer/cancel.text.slim
app/views/change_request_mailer/create.html.slim
app/views/change_request_mailer/create.text.slim
app/views/change_request_mailer/decline.html.slim
app/views/change_request_mailer/decline.text.slim
app/views/notebook_mailer/feedback.html.slim
app/views/notebook_mailer/feedback.text.slim
app/views/notebook_mailer/share.html.slim
app/views/notebook_mailer/share.text.slim
app/views/notebook_mailer/share_non_member.html.slim
app/views/notebook_mailer/share_non_member.text.slim
app/views/subscription_mailer/daily_subscription_email.html.slim
app/views/subscription_mailer/daily_subscription_email.text.slim

Testing of the daily emails is PARTIALLY blocked by #464 I was able to test several paths, but haven't figured out what path of execution is causing the subscription bug for only my account and not the other test accounts.
Uses .blank? because that accounts for nil, '' and a string of spaces only
Feedback/Change Request emails fully tested
Closes #440

Org in email

---

app/assets/stylesheets/styles.scss
app/controllers/admin_controller.rb
app/views/admin/index.slim
app/views/admin/reindex.slim
app/views/admin/run_reindex.slim
config/routes.rb

Allow admins to run a reindex (with useful errors) in the UI

---

app/assets/javascripts/gallery.js.erb
app/assets/stylesheets/styles.scss
app/assets/stylesheets/variables.scss
app/controllers/admin_controller.rb
app/views/admin/import.slim
app/views/admin/import_upload.slim
app/views/admin/index.slim
config/routes.rb

This allows you to import a bunch of notebooks into the gallery assuming the meet the requirements of the file format and have the appropriate metadata.  The rails tar processing library has some quirks though so I will need to better document it's shortcomings once I figure out what exactly they are.  Not something I can fix in the ticket but can throw an exception in some cases which I haven't figured out the bounds conditions for.
Closes #470
Closes #40

Import notebooks

---

app/assets/javascripts/gallery.js.erb
app/assets/stylesheets/styles.scss

Changed error message icon to times icon instead of checkmark and adjusted spacing of the container.
Closes #481 
Now:

Search Filter Error Fix

---

app/views/application/_notebook_json.json.jbuilder

Allow notebook json support empty creators and updaters

---

app/views/revisions/index.slim

To Repo. If you go to /change_requests/all, see the change request I made, if you go to that notebook's revisions, you'll see no "- from Change Request {blah}".
Closes #500

Change Request Link Rollback

---

Gemfile.lock

Address a gem that was yanked and re-published

---

app/assets/javascripts/gallery.js.erb
app/views/application/_notebooks.slim
app/views/application/_search_banner.slim

Made it so when on search page that clicking on label it simulates clicking on the checkbox itself.
Closes #493

Expanded Search Toggles

---

app/views/application/_notebook.slim

@manfromjupyter - Try how about this variation
Closes #516

Code cell pagination patch

---

app/assets/javascripts/gallery.js.erb
app/views/change_requests/show.slim
app/views/layouts/beta_layout.slim
app/views/layouts/layout.slim
app/views/notebooks/_notebook_info_jumbotron.slim

Mobile dropdown
Notebook dropdown
Help Dropdown
User/Gear dropdown
Notebook gear dropdown
Closes #475

Change from "Toggle" to "Expand/Collapse" for a bunch of menus

---

app/assets/stylesheets/styles.scss
app/views/application/_tags_edit.slim
app/views/application/_tags_view.slim

Also have "No Tags" in screenreader only text
closes #391

Always have a "Tags" label

---

app/assets/javascripts/login.js
app/models/user.rb
config/initializers/devise.rb
db/migrate/20210402115836_add_devise_lockable.rb

Implement Devise Lockable

---

app/assets/stylesheets/styles.scss
app/views/application/_notebooks.slim
app/views/groups/show.slim

When all notebooks are private/deprecated
Closes #522

Allow showing of private/deprecated in group display

---

app/views/application/_external_resources.slim

Make the '+' icon for external resources ignored by screen readers

---

app/assets/javascripts/run_in_jupyter.js.erb

Fix an array index from "0" to "i"

---

app/views/change_request_mailer/accept.html.slim
app/views/change_request_mailer/accept.text.slim
app/views/change_request_mailer/cancel.html.slim
app/views/change_request_mailer/cancel.text.slim
app/views/change_request_mailer/create.html.slim
app/views/change_request_mailer/create.text.slim
app/views/change_request_mailer/decline.html.slim
app/views/change_request_mailer/decline.text.slim

Also use .blank? rather than = nil to account for "       " type comments
Closes #523

Clean up emails to say when the "owner" didn't leave a comment

---

app/controllers/application_controller.rb
app/controllers/notebooks_controller.rb
app/models/notebook.rb
app/views/application/_notebook.slim
app/views/application/_notebooks.slim
app/views/static_pages/layout_dropdown.slim
config/settings.yml

Merge after #563 
Closes #564 
Closes #565

Optional notebook pagination

---

script/migrate_to_db_storage.rb

Fix migrate to db

---

app/assets/javascripts/notebook_actions.js.erb

Fix Star toggle

---

app/views/application/_notebook_json.json.jbuilder

Add tags to /notebooks.json endpoint

---

lib/to_bool.rb

Convert from FixNum to Integer

---

app/controllers/application_controller.rb
app/controllers/notebooks_controller.rb
app/views/application/_feedback_json.json.jbuilder
app/views/application/_feedbacks.slim
app/views/notebooks/_notebook_info_jumbotron.slim
app/views/notebooks/feedbacks.json.jbuilder
app/views/notebooks/feedbacks.slim
config/routes.rb

Expose historical feedback to owners and editors of a notebook

---

app/controllers/notebooks_controller.rb
config/routes.rb

Closes #551
Relates to #550 (allows you to pull the list programatically)

JSON endpoints for components of the metrics page

---

app/controllers/change_requests_controller.rb
app/views/application/_notebook.slim

Fixes some pagination related bugs

---

app/controllers/change_requests_controller.rb

Resolve the downloading of change requests issue

---

app/views/application/_cell.slim
app/views/application/_external_resources.slim
app/views/application/_notebook_metadata_metrics.slim
app/views/code_cells/show.slim
app/views/groups/show.slim
app/views/notebooks/_notebook_info_jumbotron.slim
app/views/reviews/show.slim
app/views/subscriptions/index.slim
app/views/tags/show.slim
app/views/users/show.slim

Changed all ref to rel

---

app/views/revisions/index.slim

Added screenreader only text for metadata Revision page cells

---

app/views/modals/_notebook_actions.slim
app/views/modals/_upload.slim

Closes #198 
Added label for screenreaders that allow them to better understand multi-modal forms

Proceed Label on multiple-dialog forms

---

app/assets/stylesheets/modals.scss
app/views/modals/_upload.slim

Upload Checkbox Tweak

---

app/assets/javascripts/gallery.js.erb
app/assets/stylesheets/styles.scss
app/views/users/index.slim

Added way to toggle first column of /Users to show emails instead of usernames

---

app/views/application/_reviews.slim
app/views/change_requests/all.slim

Closes #619 
- Tried to make reviews and change request as close as possible with one another
- Added a data-sort to the change request column which I believe was what was undoing the sort we were adding lines before
- Added class to the tables that fixes styling

All change request sorting

---

app/assets/javascripts/notebook_actions.js.erb

Fix to allow deletion of notebooks from the metrics and code cells page

---

app/controllers/preferences_controller.rb
app/controllers/subscriptions_controller.rb
app/controllers/user_preferences_controller.rb

Also checks a couple other major places to ensure the user is logged in before attempting to display the pages
Closes #667

Ensure user is logged in before looking at the user_preferences, jupyter_preferences of a couple other things

---

app/assets/javascripts/run_in_jupyter.js.erb
app/views/environments/_jupyter_user_interface.slim
app/views/environments/modal.slim
config/settings.yml

This allows you to override the default UI, define additional UIs, rename them, all to your preference
Closes #669

Make Jupyter UIs a configuration option

---

app/views/notebooks/_ownership_autocomplete.slim

Makes Group and User auto-complete during change ownership case insensitive
Closes #673

Make search for users and groups during change ownership case-insensitive

---

app/controllers/notebooks_controller.rb

Pass all attributes as part of the gallery metadata on download.  This only adds fields it does not affect any that are already there
Closes #567

Pass full metadata on download

---

app/helpers/notebooks_helper.rb
app/views/application/_notebook_tile_small.slim
app/views/application/_table_nb_description.slim
app/views/notebooks/_notebook_info_jumbotron.slim
config/settings.yml

Alternative way to Close #650
Closes #681

Allow admins to turn off HTML descriptions

---

app/assets/stylesheets/styles.scss

Fixed Markdown for descriptions

---

app/controllers/application_controller.rb
app/controllers/groups_controller.rb
app/controllers/languages_controller.rb
app/controllers/notebooks_controller.rb
app/controllers/tags_controller.rb
app/controllers/users_controller.rb
app/models/notebook.rb
db/migrate/20220927143400_add_notebook_deprecated.rb

Make deprecated a pre-computed field on notebooks for faster filtering

---

lib/package_grep.rb

Limit counting of Python package usage to import * and from * import

---

app/controllers/languages_controller.rb
app/controllers/tags_controller.rb
app/models/notebook.rb
app/models/tag.rb
app/views/languages/index.json.jbuilder
app/views/tags/index.json.jbuilder

Languages.json is now correct
Tags.json is now complete
both respect show_deprecated (with false a default)

Closes #708

---

config/database.yml

Provide example configuration for using SSL with mysql connection

---

app/models/suggested_notebook.rb

Allow suggested notebooks to work for non-specific sources

---

app/assets/javascripts/notebook_actions.js.erb

Use MakeAlert to display a message when you star/unstar a notebook

---

app/assets/javascripts/notebook_actions.js.erb

Improve error message when public/private toggle fails

---

app/assets/stylesheets/styles.scss
app/views/layouts/layout.slim
app/views/notebooks/_notebook_info_jumbotron.slim
app/views/revisions/show.slim

Haven't been table to test to see if alerts work when the page is deprecated but when not deprecated it works now.. Can confirm.

Made it so inline errors appear when not deprecated

---

app/controllers/users_controller.rb
app/views/reviews/index.json.jbuilder
app/views/users/groups.json.jbuilder
app/views/users/groups.slim

Added json enpoints to users/groups and reviews

---

app/models/notebook.rb
app/views/layouts/layout.slim

Remove debugging and fix a rails 6.1 bug

---

app/controllers/notebooks_controller.rb
app/views/modals/_notebook_metric_details.slim
app/views/notebooks/notebook_metrics.slim

Open to ideas for changing color but downloads are similar to runs so green for now 
Closes #193

Add downloads to the notebook metric page

---

app/controllers/admin_controller.rb

Fix recommender summary

---

app/assets/javascripts/gallery.js.erb
app/views/static_pages/home.slim

Also centralize most of the tab loading code to one function
Closes #760 
Activating tabs by click, enter key and space still works too

Make sure the last tab that was clicked on is the one that sticks

---

Gemfile
Gemfile.lock
app/assets/stylesheets/styles.scss
app/views/application/_notebook.slim
app/views/application/_notebooks.slim
app/views/application/_notebooks_home.slim
app/views/users/index.slim

Now the pagination links must be styled again

Step 1 in removing the will_paginate-bootstrap

---

app/assets/javascripts/groups.js
app/assets/javascripts/notebook_actions.js.erb
app/models/group.rb
app/models/notebook.rb
app/views/modals/_new_group.slim
app/views/notebooks/_notebook_info_jumbotron.slim

group names limited to 100 to prevent overflow problem
Closes #748

Limit length of group and notebook names

---

app/assets/javascripts/notebook_actions.js.erb
app/controllers/admin_controller.rb
app/controllers/notebooks_controller.rb
app/controllers/tags_controller.rb
app/mailers/subscription_mailer.rb
app/models/notebook.rb
app/models/suggested_tag.rb
app/models/tag.rb
app/models/user.rb
app/validators/restricted_tag_validator.rb
app/views/application/_notebook_json.json.jbuilder
app/views/application/_notebook_listings.slim
app/views/application/_notebooks.slim
app/views/application/_tags_edit.slim
app/views/application/_tags_view.slim
app/views/modals/_notebook_actions.slim
app/views/notebooks/index.rss.builder
app/views/notebooks/recommended.json.jbuilder
app/views/notebooks/recommended.slim
app/views/subscription_mailer/daily_subscription_email.html.slim
app/views/subscription_mailer/daily_subscription_email.text.slim
app/views/subscriptions/index.slim
app/views/tags/index.json.jbuilder
app/views/tags/index.slim
app/views/tags/show.slim
app/views/users/detail.slim
test/controllers/tags_controller_test.rb

Prepare codebase for normalization of the tag field Closes #463
Related to #360

Make the usage of "tag" less ambiguous throughout the code

---

app/assets/javascripts/gallery.js.erb
app/assets/javascripts/notebook_actions.js.erb
app/models/tag.rb

1 - Makes it harder for that to occur by changing the field tokenizer 
2 - Makes the serve more gracefully handle errors from the CSV Parser in the future
Closes #766

Solves issues with tags with " in them

---

app/views/layouts/layout.slim

Fixed alerts not firing on most pages

---

Gemfile
Gemfile.lock
app/helpers/notebooks_helper.rb
app/views/layouts/layout.slim

Cleanup markdown pipeline

---

app/assets/javascripts/gallery.js.erb
app/views/static_pages/home.slim

Does not affect forward/back browser activity
Closes #780

Allow homepage tabs to be bookmarked/linked to directly

---

app/assets/javascripts/common.js
app/assets/javascripts/login.js
app/assets/stylesheets/modals.scss
app/views/modals/_login_modal.slim

Uses makeAlert for the login modal errors

---

app/views/environments/modal.slim

- Firefox error where the request was not completing and the browser redirected to a get request for form submission 
- Properly handle errors saving an environment
Closes #804 
Closes #805

Two environment modal fixes

---

Gemfile.lock
app/controllers/application_controller.rb
app/views/layouts/error.slim
app/views/layouts/layout.slim

Upgrade Browser gem

---

app/models/suggested_notebook.rb

Avoids MySQL Query error
Closes #810 from my testing
Or normal dev environment is not affected so need to stand this up cleanly on its own to test it.

Change from group.map to select.distinct.map for user_defeats

---

app/views/modals/_login_modal.slim

Don't know why we never allowed this

---

app/views/revisions/index.slim

nil is blank
"" is blank
Closes #670

Check for .blank? on revision.commit_message

---

app/assets/javascripts/gallery.js.erb
app/views/stages/index.slim
app/views/stages/show.slim

Also remove one of the 2 last bootbox confirmation dialogs
Closes #820

Fix deleting stages from the stage listing screen

---

app/views/application/_language_icons.slim
app/views/application/_table_nb_title.slim
app/views/languages/index.slim
app/views/subscriptions/index.slim

Fixed screenreader language for public notebooks and language icons in general
Closes #825

Public vs Private Notebook listings fix for screen readers

---

app/assets/stylesheets/styles.scss

Fixed issue where the ellipsis pagination cell was appearing with wrong background color on dark theme. Also adjusted color on hover/focus so it's more of a difference.

Pagination Theme/Accessibility fixes

---

app/views/modals/_upload.slim

Accept tags on upload of a notebook

---

app/assets/stylesheets/fork-awesome/_path.scss

Fix Forkawesome in asset pipeline

---

app/views/modals/_approve_change_request.slim
app/views/modals/_notebook_actions.slim

Checked that last revisions exist before checking for last revision's label

---

app/assets/stylesheets/styles.scss

Fixed coloring issue of dark theme group description and size of landing page deletion icon.
Closes #843

2 Group Cosmetic Fixes

---

app/assets/stylesheets/styles.scss
app/assets/stylesheets/variables.scss
app/views/application/_nb_stats.slim
app/views/application/_notebook_metadata_metrics.slim
app/views/layouts/layout.slim
app/views/notebooks/_notebook_info_jumbotron.slim

1. Fixed share icon for `dark theme`.
2. Fixed subscription icon on notebook jumbo on `dark theme`.
3. Fixed Tags for notebook jumbo on `ultra dark theme`.
4. Fixed Admin Import Notebooks page on `dark theme`.
5. Fixed header icons on hover on `dark theme`.

5 cosmetic Theme fixes

---

app/mailers/application_mailer.rb
config/settings.yml

Closes #860 
@mcrutch is this what you were thinking?

Setup custom email headers

---

app/assets/stylesheets/modals.scss
app/assets/stylesheets/styles.scss

Closes #868 
Confirmed it's working for all inlined forms and handful of modal forms still working appropriately.

Fixed coloring of ultra dark theme inlined forms that have feedback functionality

---

app/assets/stylesheets/styles.scss

Fixed wrapping issue on rare searches

---

app/assets/stylesheets/modals.scss
app/assets/stylesheets/styles.scss
app/views/modals/_login_modal.slim

Fixed remember me checkbox

---

app/assets/javascripts/gallery.js.erb
app/assets/stylesheets/styles.scss
app/controllers/notebooks_controller.rb
app/views/application/_search_banner.slim
app/views/layouts/layout.slim
app/views/notebooks/advanced_search.slim
app/views/static_pages/home.slim

Closes #685 
Relates to #873 
@manfromjupyter What else do you think needs to go here?  And you can style how you want to get here, but at least this gets you part of the way there.

Show expanded advanced search form on empty search query

---

app/assets/javascripts/notebook_actions.js.erb

Share notebook validation fix

---

config/settings.yml

Not to be merged until after final Notebook v7 release

Updates to support Notebook v7, Labv4, NBClassic

---

app/assets/javascripts/run_in_jupyter.js.erb
app/views/modals/_run_in_jupyter.slim

Fix Run In Jupyter overwrite confirmation dialog

---

app/assets/stylesheets/styles.scss

Fixed long notebooks in headings and tables

---

app/views/revisions/index.slim

Hid Option Labels on Revision History page if empty

---

app/assets/javascripts/notebook_actions.js.erb
app/views/notebooks/_notebook_info_jumbotron.slim
app/views/notebooks/_notebook_jumbotron_title.slim

Add validation to inline title and description edit

---

app/controllers/groups_controller.rb

Fix users not found error on group save

---

app/assets/javascripts/groups.js
app/controllers/groups_controller.rb
app/views/modals/_manage_group.slim

Allow for deletion of groups without any notebooks

---

app/assets/javascripts/run_in_jupyter.js.erb

Make the name of environments a label

---

app/views/users/summary.slim

Fix what broke with the reset button

Fix issue where user summary reset button didn't work after submission

---

app/controllers/notebooks_controller.rb
app/views/notebooks/_notebook_recommendation_jumbotron.slim

pre-load More Like this and Users Also Viewed on notebook show

---

config/initializers/gallery.rb

If using database storage don't create cache, repo, staging, etc..

---

app/views/notebooks/_notebook_info_jumbotron.slim
config/initializers/gallery.rb

Support for custom banner at the top of the notebook jumbotron

---

app/views/layouts/layout.slim
app/views/static_pages/layout_dropdown.slim

Hide learning menu if nothing is configured

---

app/assets/javascripts/gallery.js.erb

fix admin import notebooks form button disable
relates to #848

Make import notebook form disable submit

---

app/views/modals/_notebook_actions.slim

Closes #953 
Verified it wasn't used.

Removed extra unused Propose Comment Id

---

app/assets/stylesheets/variables.scss

Confirmed works on Firefox, Edge, and Chrome.
Are we okay with notebook links being orange by default then blue on hover/focus on the default theme?
Closes #965

Link Color Inconsistencies

---

app/controllers/notebooks_controller.rb

Closes #958 
Not the perfect solution. Perfect solution would also exclude the notebook from appearing in recommendations at all and then cause front end errors now letting users lose the deprecation reasoning text they typed if that failed. That all being said, here is the quick solution to prevent saving deprecation status from both the UI and from console users when the alternate notebook ID contain the notebook's ID itself.

Deprecated Notebooks can't set Alt Notebook as itself

---

.gitignore
app/assets/javascripts/gallery.js.erb
app/controllers/notebooks_controller.rb
app/mailers/notebook_mailer.rb
app/views/application/_notebook_run.slim
app/views/modals/_upload.slim
app/views/notebooks/_notebook_info_jumbotron.slim
config/initializers/gallery.rb
lib/seeder.rb

This PR aims to resolve some discrepancies between the default app and the app with custom extensions.
- new files added to the `.gitignore`
- render partials for custom templates
- `Seeder` module can now load `seeds.rb` files from other extensions.

Refactor for compatibility with custom extension

---

app/models/review.rb

Reverts nbgallery/nbgallery#1011

Revert "fix bug"

---

app/assets/javascripts/gallery.js.erb

Really simple addition of the loading gif when adding and removing users as recommended reviewers.

Added Loading GIF to adding and removing users as a indicator of processing

---

app/controllers/languages_controller.rb
app/controllers/notebooks_controller.rb
app/controllers/tags_controller.rb
app/controllers/users_controller.rb
app/views/reviews/show.slim

1. added functionality to filtering options on the user, language, tag notebook listings
2. fixed notebooks that have metadata changes before reviews are proposed, verified status is not changed if review process completes
3. Claim button disappears on functional reviews for the recommended reviewer if the reviewer hasn't run the notebook.

Review process bug fixes & Verified filters added for user, language, and tag notebook listings

---

app/assets/javascripts/gallery.js.erb
app/assets/stylesheets/styles.scss
app/controllers/application_controller.rb
app/controllers/groups_controller.rb
app/controllers/languages_controller.rb
app/controllers/notebooks_controller.rb
app/controllers/reviews_controller.rb
app/controllers/revisions_controller.rb
app/controllers/tags_controller.rb
app/controllers/users_controller.rb
app/models/notebook.rb
app/views/application/_notebooks.slim
app/views/application/_search_banner.slim
app/views/notebooks/_notebook_unapproved_alert.slim
db/migrate/20250508195408_add_unapproved_to_notebooks.rb

1. Unapproved notebooks should not be viewable unless filtered.
2. New boolean field for notebooks.

Hiding unapproved notebooks from public view

---

app/models/notebook.rb
app/views/application/_notebook_run.slim

active? was not properly writen to be overridden by an extension these changes fix this.

Revise active method so it can be properly overridden

---

app/models/notebook.rb

Fixing the unapproved? getter method in notebook model (specifically the possible case of null which breaks group and user notebook listing display)

Fix unapproved?
