nbgallery/nbgallery

docker-entrypoint.sh

Fix variable used to determine if DB is found: GALLERY__MYSQL__USERNAME instead of GALLERY__MYSQL__USER

Fix variable typo in init script

---

app/models/user.rb

Email validation against the allowed_domains list didn't work when there was more than one allowed domain.
This is my first pull request ever, so bear with me if I've made mistakes.

Fix email validation against the allowed_domains list

---

app/views/environments/modal.slim
app/views/layouts/beta_layout.slim
app/views/layouts/layout.slim
app/views/users/summary.slim
app/views/warnings/show.slim

Added placeholders to a handful of input fields missing them (Accessibility Improvement) as well as made a header fix consistent with the rest of the web app (and applied it to the beta version). Lastly made a fix to the admin site banner to make it reveal the date now after a warning has been created.
Covers JUP-349 & JUP-357

Accessibility improvements #1 and site banner improvement

---

app/assets/stylesheets/formatters.scss
app/assets/stylesheets/styles.scss
app/assets/stylesheets/variables.scss
app/controllers/user_preferences_controller.rb
app/helpers/application_helper.rb
app/helpers/user_preference_helper.rb
app/models/user_preference.rb
app/views/change_requests/all.slim
app/views/change_requests/show.slim
app/views/languages/index.slim
app/views/layouts/beta_layout.slim
app/views/layouts/layout.slim
app/views/notebooks/_notebook_info_jumbotron.slim
app/views/preferences/index.slim
app/views/revisions/index.slim
app/views/subscriptions/index.slim
app/views/user_preferences/index.slim
app/views/users/show.slim
app/views/warnings/show.slim
config/routes.rb
config/settings.yml
db/migrate/20191202192605_create_user_preferences.rb
test/controllers/user_preference_controller_test.rb
test/fixtures/user_preferences.yml
test/models/user_preference_test.rb

- Created NBGallery (User) Preferences
- Users can now set their site theme to "dark", "grayscale", "ultra-dark", or "juicy".
- Additional options to make all text bigger and make everything have more contrast. (Can be applied to default NBGallery skin or to one of the 4 themes mentions above).
- Did some catch up fixes
- Fixed a minor issue where internet explorer and microsoft edge browsers had a space in their css selector in the body class.
- Changed coloring of many links, almost all tags, and a handful of other elements to ensure all elements have appropriate contrast (accessibility).
- Changed NBGallery logo (image) to text.
-And have everything set up to support changing one's timezone or enabling ultimate accessibility mode, but unfortunately don't have time to fully implement …

Accessibility 7: Added NBGallery Preferences, fixed contrast of all elements, and played some catchup

---

app/assets/stylesheets/modals.scss
app/assets/stylesheets/styles.scss
app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/views/application/_notebook_listings.slim
app/views/change_requests/index.slim
app/views/layouts/beta_layout.slim
app/views/layouts/layout.slim
app/views/notebooks/_notebook_info_jumbotron.slim
app/views/stages/show.slim
app/views/users/detail.slim
app/views/users/groups.slim
app/views/users/summary.slim

- Changed all user links to use the link_to_user helper and included logic for displaying org on title if they exist for said user (so removed a bit of tech debt too)
- Changed the notice flash messages to success flash messages when doing user model changes.
- Is too wordy to include "belongs to org: Engineering" for all user links for screenreader users so decided to just add it to the header on the User Summary page (so a minor change there too).
- Did some catch up for the dark and ultra dark themes
Tested everything but confirming the success message appears after a user is created and their profile is updated, but it does work every time for updating users and creating users and it was of the same code format.

User Link Tech Debt fix/cleanup and hover fix when user has no org

---

app/assets/stylesheets/styles.scss
app/views/application/_author_rep_trophy_icon.slim
app/views/groups/show.slim
app/views/modals/_notebook_actions.slim
app/views/tags/show.slim
app/views/users/show.slim
app/views/users/summary.slim

- Added links on the /users/{ID} and /users/{ID}/summary page to the edit and detail page for the user for admin users.
- Hid icons found in carousels from screenreaders.
- Cleanup of CSS for group css for icons.
- Cleanup of classes for notebook actions modal slim file.
- Changed color of warning icon for change requests page for all themes.
- On larger-text/font mode, made the search icon on home page, better aligned.

Accessibility tech debt and helped provide more quick links for admin users

---

app/assets/stylesheets/styles.scss
app/controllers/static_pages_controller.rb
app/views/application/_nb_stats.slim
app/views/application/_notebook_listings.slim
app/views/application/_table_nb_description.slim
app/views/application/_tags_view.slim
app/views/environments/index.slim
app/views/notebooks/_notebook_info_jumbotron.slim
app/views/notebooks/_notebook_jumbotron_title.slim

- Added IDs to home page tab listings for better targeting
- Removed IDs in notebook listings where they clearly shouldn't have been as numerous elements were existing simultaneously with the same ID.
- Added some screenreader-only text to the environments page and notebook jumbrotron page
- In addition made adjustments to the tag edit icon under the hood to follow the same coding and html as the other two edit icons (edit title and edit description.
Has been tested and all changes have been done through global find/replace so nothing is using the old spelling or ID of these notebook listings.

Home page/Notebook Listing id fixes and screenreader text injections on a few icons

---

app/assets/stylesheets/styles.scss
app/views/application/_notebook_metadata.slim
app/views/notebooks/_notebook_info_jumbotron.slim
app/views/notebooks/_notebook_jumbotron_title.slim

Brought back functionality for admins on private pages and made lock icon on jumbotron pages bigger and moved them near title for product consistency
P.S. Tested and I recommend using notebook # 24 for testing, but really any notebook not yours can be made private then public again no problem so any really work.

Brought back functionality for admins on private pages and minor tweaks to private icon on jumbotron page

---

app/views/users/index.slim

Tested result with 3 and 100 objects per pagination.. Screenshots below are what it looks like when we paginate after 3.
NOTE - didn't add any filtering abilities, just sorted it by username (instead of id which is how it was done before)

User-Pagination: Made it so the users page paginates if you have more than 100 users

---

app/models/notebook.rb

This will allow the keyword: type searching in the search field.  This could also be used to power an advanced search form but we will need to expose the syntax somehow (looking at you @manfromjupyter to do GUI work to expose the users to this power)

Keyword search boosting for specific fields

---

app/controllers/application_controller.rb
app/controllers/static_pages_controller.rb
app/views/application/_notebook_listings.slim

- Moved the home page tab table generation method to the main application controller (pretty much only change)
- Added id to table for notebook listings generated by a search
Tested home page tabs, searches, and all pages that generate notebook listings (all look good now)

Hotfix-1: Fixed the issue where non-home page notebook listings were returning an error

---

app/views/groups/index.slim
app/views/users/groups.slim

- Revealed all groups on user's groups page
- Sorted results on User's groups page by number of owned notebook so it matches the functionality of the /groups page
- Updated the /groups page to include a link to the User's group page if users want to see all of the groups of theirs not included because they contain no notebooks within them

Group visibility changes

---

app/controllers/application_controller.rb

Browser-title-fixes: If objects are returned as nil due to the browser not being modern, made it so it won't error out
Majority of changes below are just due to being tabbed due to nesting the code in an if/else.
Tested IE and Chrome.

Browser-title-fixes: If objects are returned as nil due to the browser not being modern, made it so it won't error out

---

app/assets/javascripts/gallery.js.erb

When clicking on the expandable search icon on mobile/magnified zoom, the cursor will automatically pop up in the input field for the search so you can just begin immediately typing.

Header-Search-on-mobile: Made it autofocus when activated

---

app/views/groups/index.slim

Groups-alert-fix: Made it so the /groups alert actually shows up now. Had wrong math before

Groups-alert-fix: Made it so the /groups alert actually shows up now. Had wrong math before

---

config/cronic.d/jobs.rb
config/environments/development.rb
config/initializers/sunspot.rb
config/settings.yml
docs/scheduled_jobs.md

Cron schedules are defined in config instead of being hard coded. Added ability to enable / disable sunpot in development environment

Cron schedules in config and ability to disable sunpot in dev

---

app/assets/javascripts/notebook_actions.js.erb
app/assets/stylesheets/modals.scss
app/controllers/groups_controller.rb
app/controllers/notebooks_controller.rb
app/controllers/revisions_controller.rb
app/helpers/notebooks_helper.rb
app/models/jupyter_notebook.rb
app/models/notebook.rb
app/views/modals/_notebook_actions.slim
app/views/notebooks/_notebook_info_jumbotron.slim
app/views/notebooks/_notebook_jumbotron_title.slim
config/routes.rb
config/settings.yml

A few changes in this pull request:
- Ability to allow users to propose their own reviews - can be enabled / disabled by config value. By default, it is disabled
- Show gray badge when a previous revision of a notebook has been fully reviewed (and the current revision hasn't)
- Ability to customize stripping of notebook data in extensions
- Metadata endpoint for revisions
- A few bug fixes: users couldn't change group membership, no error was shown if the editing of notebook descriptions failed and CSS padding on modals fix

Ui changes

---

app/assets/stylesheets/styles.scss
app/views/change_requests/show.slim
app/views/code_cells/show.slim
app/views/notebooks/notebook_metrics.slim

Added return link for code cells and made the rest more consistent with one another. Also removed redundant accessibility labels.

Added Return link for Code Cells & did cleanup for others

---

app/views/application/_tags_view.slim

GITHUB-149: Made tag edits only possible if user signs in

GITHUB-149: Made tag edits only possible if user signs in

---

docs/configuration.md

Without setting a correct password with the minimum length, admin user login fails with a 500.

Document minimum password length

---

app/controllers/notebooks_controller.rb

I am just using the base_url at this time because that ensures it caputres the URL it actually came from for easiest flexibility. I am open to other ideas on this though.

Add Gallery_url to Notebook metadata when sending to Jupyter

---

app/views/application/_notebook_run.slim

GITHUB-174: Made run in Jupyter banners no longer appear for anonymous users

GITHUB-174: Made run in Jupyter banners no longer appear for anonymous users

---

app/helpers/notebooks_helper.rb

Fix for showing when a notebook has previous revisions that have been reviewed when the review label is different from the revtype

Bugfix when review labels are different from revtype

---

config/environments/production.rb

Production docker image wasn't working with log rage (but running in production mode was) investigate further but for now turn off lograge

turning off lograge

---

Gemfile
Gemfile.lock

Samesite is not supported in the Rails 4 session manager
using rails_same_site_cookie to solve that.
Closes #276
Background information for same-site: https://www.chromium.org/updates/same-site
NOTE: Chrome only supports this over HTTPS

Patch for same-site cookie header

---

app/assets/javascripts/gallery.js.erb

Fixed issue #284 where toggling to notebook view on Group pages more than one time causes sparkline graphic to disappear

Toggling back and forth on group view notebooks no longer causes sparkline disappearance 

---

app/controllers/users_controller.rb

protected by the devise token rather than authentication
closes #299

Allow anonymous access to the oauth endpoint because it is

---

app/assets/javascripts/gallery.js.erb
app/assets/javascripts/notebook_actions.js.erb
app/assets/stylesheets/styles.scss
app/controllers/notebooks_controller.rb
app/controllers/resources_controller.rb
app/models/notebook.rb
app/models/resource.rb
app/models/user.rb
app/views/application/_external_resources.slim
app/views/modals/_notebook_actions.slim
app/views/notebooks/_notebook_info_jumbotron.slim
config/routes.rb
config/settings.yml
db/migrate/20200903122609_create_resources.rb
test/fixtures/resources.yml
test/models/resource_test.rb

@manfromjupyter Take a look through this.  The "External Links" section only appears if
a) There are links or
b) The user viewing the notebook has edit priv (including admin) so they have access to the + icon
Dialog copies error message method from a different dialog, so should be accessible, unless I copied one that wasn't.
Simplistic Javascript validation and more robust validation for URL on the backend
Doesn't prevent double posting right now but, they are easy to delete...What if they want two titles to the same doc or something.
Closes #153

Resource links

---

app/views/application/_alert_container.slim

Closes #309 
This is built into devise (it only returns notice and alert) and the only way to fix this is a little hacky - https://stackoverflow.com/questions/32444342/devise-flash-message-being-notice

Change devise alert and notice to error and info for proper display

---

app/assets/javascripts/notebook_actions.js.erb

Might look like it's broken when testing but before this change, clicking it causes a little stutter and then it doesn't open. Just think it has to do with my environment of this and emails not working right so far.
Closes #324

Email Notebook doesn't cause '#' to appear in URL now.

---

app/assets/stylesheets/styles.scss

Closes #335 
Can test by going to /notebooks/41-typsetting-equations.
And then for sanity can check a code cells page. Those are the only places with these elements.
Before:
After:

GITHUB-335: Fixed it so notebooks with bad html don't cause code blocks to break

---

app/assets/stylesheets/styles.scss
app/controllers/notebooks_controller.rb
app/models/review.rb
app/views/modals/_notebook_actions.slim
app/views/notebooks/_notebook_info_jumbotron.slim

- Fixed home page and External Resources for ultra dark theme
- Fixed autonomination nightly_computation of reviews so already queued notebooks aren't recreated again causing subscription emails to keep sending off every morning despite there not being any new change.
- Added error block placeholders in the External Resource modal and Deprecation Status Banner
- Gave users with editor permissions on notebooks the ability toggle public/private and share with other users.

Minor fixes to themes, reviews autonomination, error handling in a couple modals, and editor permissioning

---

app/assets/stylesheets/styles.scss
app/assets/stylesheets/variables.scss

Closes #341 
NOTE - May want to merge !319 first as it contains other dark theme fixes. 
Went to every page, tested modals, and made sure contrast is applied everywhere now and the orange primary color for this theme is applied where all non-tabled links are (exception of /users/reviews page because it looks better in the headers as blue, we can we  play with it).

GITHUB-341: Made numerous changes to Dark theme for better contrast and consistency.

---

docker-compose-with-jupyter.yml

This should be a very simple swap and everything seems to work with the base-image just swapped in. This should fix #334

GITHUB-334: Update docker-compose YAML to use more recent base-image instead of Alpine

---

app/assets/javascripts/notebook_actions.js.erb
app/assets/stylesheets/modals.scss
app/controllers/notebooks_controller.rb
app/views/modals/_notebook_actions.slim
db/migrate/20201014151211_change_reasoning_to_be_text_in_deprecated_notebooks.rb

Switched Deprecated Notebook's SQL table reasoning column from t.string to t.text so will no longer return rails/MYSQL error: 'ActiveRecord::StatementInvalid - Data too long for column'
Test by either inspecting deprecate_notebooks table or adding a huge amount of text to a deprecation status.
Closes: #323

GITHUB-323: Deprecated Notebook's SQL table reasoning column no longer return Errors

---

.gitignore
app/assets/javascripts/run_in_jupyter.js.erb
app/controllers/environments_controller.rb
app/views/environments/_environment.json.jbuilder
app/views/environments/_jupyter_user_interface.slim
app/views/environments/index.slim
app/views/environments/modal.slim
db/migrate/20201106152806_add_interface_to_environment.rb

Allow extensions to set which Jupyter UI notebooks should open in
Allow users to specify what UI they want their "Run in Jupyter" button to use
Compatible with jupyterlab-nbgallery 0.2.0a3 and above Jupyterlab extensions
Closes #279 
Note: Allows for us to change the default in the future for users who haven't changed the value for their "classic" environments (because those still default to NULL from the extension, but can be manually forced to classic by editing the environment)
Will not change it just because they visit Lab (only new environments created as a result of going to Lab are set to lab)

Jupyter Classic vs Jupyter Lab UI for "Run"

---

db/migrate/20201118162416_add_primary_to_groups_users.rb

Closes #357 
Intermediate tables MUST have singular primary key in order to be used in a cascading delete it seems.

Allow users who are part of a group to be deleted

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/gallery.js.erb
app/assets/stylesheets/application.scss
app/assets/stylesheets/styles.scss
app/views/users/summary.slim
app/views/warnings/show.slim

This datepicker uses glyphicons and can more easily be styled
Possible solution to #352 by using a different, non-image based, datepicker
The max-width is because the datepicker seems to build it's size as a factor of the input field width and the input field for the warnings page is massively long.

Change to bootstrap-datepicker for styling reasons

---

app/views/modals/_notebook_actions.slim

Closes #321. May not be enough information but will help get back on track the vast majority of people that would get stuck here. On both Firefox and Chrome browser generates an error there that looks as follows and tells them to use a valid url.

External Resources: Added type of url to field so browser throws error accordingly

---

app/assets/javascripts/gallery.js.erb
app/controllers/stages_controller.rb
app/views/stages/index.slim
app/views/stages/show.slim

Fixed an issue where deleting a staged notebook from the stages/uuid would redirect to the page you're already on and 404. This solution now exactly mirrors that of the notebook delete. I have plans to redo all of the way we do confirmation dialogs in a more accessibility friendly way and way that matches our styling more but for now this at least gets them doing the same thing.
Closes #396

Fixes 404 when deleting Staged Notebook from /stages/uuid

---

app/assets/stylesheets/formatters.scss

Made it so horizontal scroll bars no longer appear:
My attempt at editing the markdown syntax highlighter/markdown plugin to make it look like the current code block but with line numbers and the above issue of wrapped lines having same text indent applied to it was not successful. Best I could do with just a CSS hack for the record was as follows. Changes were not merged for obvious reasons.
Will address these line number and other changes later, but for now leaving the code on here just to wrap them. If we want to turn the horizontal scrollbar functionality as something users can enable in their NBGallery preferences, just let me know, I think we need this out of he box though, although would be a lot better with line numbers or that margin fix.
Another thing to note, different version …

Code cell changes

---

app/controllers/static_pages_controller.rb
app/views/application/_html_head.slim
app/views/static_pages/opensearch.erb
config/routes.rb

Closes #385 or at least it should. Tested but couldn't get to work due to what I presume is a caching issue. I've triple checked to make sure it is all there and going to {SITE}/opensearch.xml loads it successfully. Also made sure it's exactly formatted like one of our coworkers made for another system (both the file and the meta tag). I think this is good just might not be registered because of the noindex nofollow or something. 
Anyway to know if it's working, when selecting from available search engines, should have the nbgallery icon and when in main url of browser and typing part of the url and then hitting tab once to complete it and then tab again to enable search, the string that it says it should be searching in should say "NBGallery" not the full url of the site.

NBGallery Search Engine Customizing

---

app/assets/stylesheets/styles.scss
app/controllers/application_controller.rb
app/controllers/change_requests_controller.rb
app/controllers/notebooks_controller.rb
app/controllers/stages_controller.rb
app/models/notebook.rb
app/views/errors/bad_change_request.slim
app/views/errors/bad_notebook.slim
app/views/errors/must_accept_terms.slim

Closes #386 and #387 
Partially for legacy systems that have old notebooks with title with characters we have since deemed illegal so it better communicates with Jupyter. Whenever a user uploads a new version or accepts a change request any of the illegal characters :/\ will automatically switch to full width characters, with exception of the colon which is just a different Jupyter-friendly variant that barely looks different than the normal colon. 
In addition fixed an issue where padding was off for errors on home page and edited current error message for when a new upload has illegal characters to include the approved icons within the error message so they could copy/paste to save time.

Old title character parsing

---

app/views/environments/index.slim

Closes #428 
Fixes this: (super minor)

Environments tweak: Increased colspan of the empty environments label when user has no environments.

---

app/controllers/notebooks_controller.rb

This forces solr to reload the notebook which fixes the search permission problem
Closes #383

Trigger notebook reindex by doing a notebook.save

---

app/assets/stylesheets/styles.scss
app/views/application/_notebook.slim
app/views/application/_notebooks.slim
app/views/application/_notebooks_home.slim
app/views/users/index.slim
config/environments/development.rb

Closes #15, #399, and #401 
Added pagination after 20 notebook cells (code cells, text cells, etc). If this needs to be changed or moved up, it's an easy fix, but for testing given that the size of these 20 can vary use this as a baseline:
With breaking in 20 cell increments:
{SITE}/notebooks/86-recursion-examples is the minimum in terms of scrolling that would be required.
{SITE}/notebooks/148-visualization-earthquakes?page=4  is the maximum in terms of scrolling that I could find with these changes. Both load super easily.
Relative minimum:
Relative maximum:

Added pagination of code cells on notebooks to help load ridiculously large notebooks easier.

---

app/views/notebooks/_notebook_info_jumbotron.slim

Else show the updated date for the notebook
only used if the "updated" code is triggered
closes #208

If a revision was specified, show the updated date for that revision

---

app/assets/javascripts/notebook_actions.js.erb
app/views/modals/_notebook_actions.slim
app/views/notebooks/_notebook_info_jumbotron.slim

Closes #441
In addition fixes an issue where the deprecation submit button when editing the form does not become enabled (no disabled) after changing it from deprecated to disabled (the dropdown). Tested on Chrome and FF. Should be good to go now for all of those notebook owners.

Enabled Deprecation to all owners

---

app/views/modals/_notebook_actions.slim
app/views/modals/_upload.slim

Code Catchup: Passed variable to custom fields so user can differentiate them based on if it's coming from an upload modal vs upload new version or change request modal.

Code Catchup: Passed variable to custom fields

---

app/assets/stylesheets/styles.scss
app/views/application/_notebooks.slim
app/views/application/_search_banner.slim

On search pages now have the private and show deprecated toggles appear under the filters section.
Closes #453

Redesign-Search-Toggles

---

config/application.rb

closes #473 
@jeffyjefflabs and @mcrutch  I don't know to test this so can you let me know if this looks right or if it needs to have a different origin other than (`origins {|_source, _env| true}` that most of the other CORS policies have).

Allow GET /tags/* in CORS

---

app/views/revisions/index.slim

Don't have a notebook with 2 rows (one as create and one as metadata). But tested for ones missing reviews and one with all the things. My code should work with what happens when no reviews AND no compare current/preview column exists, just checked every notebook in database with metadata that has it and tried adding my own manipulating the metadata field of notebooks and couldn't get it to upload as a "metadata" change.
Notebook ID's to checkout for testing `ID: 537` for what all columns looks like. `ID: 464` for missing reviews column.
PS. For the record I dislike how many conditionals are in here but these changes do fix the problem.

Revision History table fix for metadata cells hanging over edge.

---

app/views/application/_search_banner.slim

1. Before checking out this branch, search for "testgerergerger", verify there is no way to see deprecated or private notebooks when searching for that.
2. Checkout branch and search for it. Verify you see the toggleable filters.
3. Enable bother and verify you see the notebook in the search results.
Closes #487

Show search filter toggles on empty notebook searches.

---

.dockerignore
.gitignore
Dockerfile.dev
config/environments/development.rb
docker-dev.sh
docs/docker.md

Cleaned up the docker documentation after actually trying it from scratch for the first time.  The old manual setup notes are pretty useless at this point, so I deleted them.  Added some support to set up an environment for doing dev inside docker, with source mounted into the container.

Docker dev updates

---

app/views/commontator/comments/create.js.erb

Reload the notebook page after the comments dialog has been closed but ONLY if a new comment has been posted
Closes #318

Reload comments

---

app/controllers/users_controller.rb
app/models/user.rb
app/views/users/summary.slim

Closes #575
Fixes All Time button to work
Allows start and or end date to be empty both in support of All Time and also to allow the user to have an open ended date range
Converts date/times to iso8601 to ensure queries are successful

Fixing User Summary

---

app/assets/stylesheets/styles.scss
app/assets/stylesheets/variables.scss

Closes #617 
- Lastly made the ultra dark themes more user friendly. Green, not purple now means success. Red, not teal, now means error. Screenshot shown below.
- For ultra dark on home page, made inactive tab color lighter
- For dark theme on tables, made link color slightly darker

More Theme Fixes

---

app/assets/stylesheets/styles.scss

Closes #409 
By removing the styles includes, all notebook listings on all themes have an underline when hovered or focused. The color on hover was a rogue color anyway as it wasn't a variable.

Consistent and accessibility-support styling of notebook titles in listings

---

app/assets/javascripts/gallery.js.erb

Closes #662 
Will make sure the environment name column and actions column are always appearing (for readability and ability to complete necessary job functions quickest).

Low vison fix for environments page

---

app/assets/javascripts/notebook_actions.js.erb
app/assets/stylesheets/modals.scss
app/views/modals/_notebook_metric_details.slim

Added buttons on bottom of metric modals to quick copy all of the user emails.
Closes #550. The only thing is this only works with HTTPS websites. The old method to do it for HTTP sites requires old browsers which we block. Maybe there is another way, but this seems to be the only way.

Quick Copy Buttons on Metric pages for all User Emails

---

app/views/application/_table_nb_description.slim

BUT, there will be more to follow on
Closes #650

Ensure that HTML descriptions that are truncated for search results don't break the display

---

app/controllers/notebooks_controller.rb
app/models/group.rb
app/models/notebook.rb
app/views/application/_notebooks.slim
config/sunspot.yml

For sanity sake I want a few more sets of eyes.  I stopped the auto-indexing so the save to the database can succeed, have an aftersave that will attempt to index the records (for both groups and users).  I am not happy with how the error message appears on the search page so I think @manfromjupyter should double check that I set the flash message correctly (it stays one screen past when the user hit the error message on a bad search)
Closes #616

Make NBGallery tolerant to SOLR failures

---

app/assets/javascripts/gallery.js.erb
app/assets/stylesheets/modals.scss
app/views/modals/_upload.slim
app/views/notebooks/_notebook_info_jumbotron.slim
config/settings.yml

Closes #531
@manfromjupyter I think we should increase the default size of the description input (height) or have it auto scale, because the second you shove a description template in there it is just lost in the noise with the scroll bar but the box doesn't enlarge itself.  Can you take a look into that.

Allow for creation of a description template

---

app/assets/stylesheets/styles.scss

Closes #738 
+ Confirmed looks good on all themes.

Fixed borders of revisions when on and off of deprecated notebook pages

---

app/views/layouts/layout.slim

All alerts now can properly appear on every page (and only once).
100% tested.

Fixed double alert issue (finally)

---

app/assets/stylesheets/styles.scss
app/views/application/_notebook_metadata_metrics.slim

Closes #542 
Ideally need to refactor our stats sections to all be styled the same way with the same container but didn't want to make this PR too big.

Fixed outline of metric and lock icons

---

app/assets/javascripts/gallery.js.erb
app/assets/stylesheets/styles.scss
app/views/users/detail.slim

- Fixed wrapping issue with users, groups, tags, and notebooks on all of the admin pages with graphs and the user details page.
- Fixed table-compression issue of users with too long of an email or username on the /users page.
Closes #793

Fixed wrapping issues in admin and user detail's tables

---

app/assets/javascripts/groups.js
app/views/groups/show.slim

Closes #301 
@manfromjupyter You are the UI man, but here is what I am thinking.  It only shows up on the listing, not with the landing page as a landing page should be self-descriptive.

Display group description on Notebook listing

---

app/controllers/notebooks_controller.rb
app/views/modals/_upload.slim
db/migrate/20230407125703_add_parent_uuid_to_notebooks.rb

Track the parent_uuid of a notebook when the notebook is uploaded using "fork notebook" from Jupyterlab extensions
Closes #711

Track parent_uuid

---

app/controllers/notebooks_controller.rb

Used to check AFTER changing the ownership which changed owner_type Threw an error when transferring from Group->User since @owner was nil
Closes #858

Only attempt to send the email if the previous owner is not nil

---

app/assets/stylesheets/modals.scss
app/views/application/_search_banner.slim

1. Currently filtering by private notebooks on search is bold where the deprecated label next to is not. Fixed that.
2. Setup proper label to form element relationship for search filters (was forgotten in #849)

Fixed accessibility issues and a cosmetic one for search filters

---

app/assets/javascripts/gallery.js.erb
app/assets/stylesheets/modals.scss

Closes #870 
The `label` change to `form label` was to fix an issue with our datatables where the Filter Results section was now sinking down into the table.

Changing search to filter results in datatables

---

app/assets/stylesheets/styles.scss

Closes #886 
Fixes 2 dark theme issues
1. Modals of tables ,example metrics tables had several components around the table invisible (white on white)
2. Edit user page had white labels on light gray backgrounds.

Fixed 2 dark theme issues

---

app/assets/javascripts/run_in_jupyter.js.erb

Closes #885
Limits base filenames (minus extension) to 220 characters so filename + "-checkpoint" + extension stays below 255 character limit

Address long filenames causing an error in Jupyter

---

.gitignore
app/models/notebook.rb
app/models/user.rb
db/schema.rb

Attempting to load the application used to require a valid connection to the database, which prevented the use of commands like `rails db:create`.
This was caused by a statement in the `User` model class that attempted to connect to the database to find out the names of the fields in the `UserSummary` class in order to define delegator methods for each of them. A similar statement in the `Notebook` class had the same effect.
This change fixes the issue by allowing this delegation to happen later during the application's runtime.
In the Notebook class, the delegated methods have been hard-coded instead of being dynamically looked up. This is because some of them used a prefix while others didn't. Thus, new attributes will note be delegated by default.
The User class was easier because it …

[config, db] Remove dependency on the database during startup

---

app/views/layouts/layout.slim

Closes #893 . Keeping the Id because it's needed for the skip link. Can't do it another way.

Replaced main section <section> with <main>

---

app/controllers/notebooks_controller.rb

Use Case:
- User A is an admin
- User A adds Trusted to a notebook
- User A stops being an admin
- User B (admin or not) tries to add tag "foo" to a notebook
- User B would be blocked because the trusted tag is no longer valid
How it's fixed
- tag.invalid is only checked for NEW tag records added to the notebook
Closes #925

Fix a trusted tag edge case

---

app/controllers/admin_controller.rb
app/views/admin/import.slim
docs/configuration.md

Hello! So I've been playing around with the admin bulk notebooks importer, and I noticed that when I use it to update existing notebooks by providing a UUID, the revision history is always `Notebook Imported by Admininistrator`.
This PR fixes this typo and other typos in the same file, as well as giving you the option to provide a custom changelog summary using the new option `changelog` in your `metadata.json` file. Thanks!

Enable changelog option in admin bulk import and fix typos

---

lib/package_grep.rb

Prevent package grep from seeing `#import foo` as a valid import

---

app/controllers/notebooks_controller.rb
config/settings.yml

Closes #578 
Queued reviews carry over to next versions if all reviews are queued AND the config to allow it is set to true. I recommend making it default functionality but adding it as a config just in case people want it.

Carry Forward Queued Reviews Config

---

app/assets/javascripts/gallery.js.erb

**References**
This fixes the enter/spacebar click functionality for https://github.com/nbgallery/nbgallery/issues/982
**Code changes**
I have changed `$(this).click();` to `this.click();` in `gallery.js.erb`
**User-facing changes**
Users who navigate using the keyboard can now click on buttons, a tags (i.e. menu items) and any element with the `.keyboard-friendly` class.
**Backwards-incompatible changes**
None

Fixed Enter/Spacebar 'click' functionality for Buttons, a Tags and .keyboard-friendly Class

---

app/controllers/notebooks_controller.rb

this fix would prevent 500 error being thrown when users do not enter any input for optional field

fix deprecate function

---

app/assets/javascripts/gallery.js.erb
app/controllers/application_controller.rb
app/views/errors/invalid_authenticity_token.slim

Resolves issue #579 
- exception handling in the case there is a CSRF token mismatch
- error template for Invalid auth token
- fixed bug on `upload_error` that wouldn't display the error msg

update error message for file uploads when session auth is invalid

---

app/controllers/application_controller.rb
app/models/notebook.rb
app/views/application/_notebooks.slim

There was a naming conflict when indexing by :title. Solr was likely using the `text` version of :title which is not compatible for sorting.
resolves #977

resolved sorting by title when searching for notebooks

---

app/assets/javascripts/notebook_actions.js.erb

Problem: The alert container was set to hidden and when an error occurred, the error message would not display.
```
div.alert-container
div.alert.alert-danger.text-center hidden="true" id="editUploadErrorWarning"
```
Solution: removed the hidden attribute for the alert container in the event an error occurred.

removed `hidden` attribute for stages#create endpoint

---

app/models/notebook.rb

If the user searches for something, the sorting order is done with Solr instead of MySQL. MySQL uses `title` and Solr uses `title_sort` so this needs to be specified.

sets the correct sorting `title` for mysql

---

app/controllers/application_controller.rb
config/environments/development.rb
config/environments/production.rb

ExceptionNotifier plugin ignores InvalidAuthenticityToken exceptions. Also added more sections to the emails.

log invalid auth token events

---

app/assets/javascripts/notebook_actions.js.erb

On some occasions this error would occur:
` Missing template notebooks/update, application/update with {:locale=>[:en], :formats=>[:html], :variants=[], :handlers=>[:raw, :erb, :html, :builder, :ruby,  :jbuilder, :slim]}`
The browser may be defaulting to HTML and attempts to render this non-existent template but the notebooks#update endpoint returns json. Adding `dataType: 'json'` explicitly tells jquery to expect a json response.

explicitly set json for dataType

---

app/assets/javascripts/gallery.js.erb
app/assets/stylesheets/styles.scss
app/controllers/application_controller.rb
app/controllers/groups_controller.rb
app/controllers/notebooks_controller.rb
app/controllers/reviews_controller.rb
app/helpers/notebooks_helper.rb
app/models/notebook.rb
app/views/application/_notebook_listings.slim
app/views/application/_notebooks.slim
app/views/application/_search_banner.slim
app/views/notebooks/_notebook_jumbotron_title.slim
db/migrate/20250306190247_add_notebook_verified.rb
lib/scheduled_jobs.rb
script/verify_notebooks.rb

- notebook entries in database are now explicitly verified or unverified in their table
- there is also a script that can be run for DBs that already have existing verified notebooks to have them be labeled as such in the table
- users can filter the search and all notebooks to only show verified notebooks
- verified notebooks are directly boosted with an increased score when searching for notebooks.
- This is all the big logical stuff I could think of doing with verified notebooks - open to suggestion or additional ideas
- I am thinking that the homepage notebooks need to also be showing verified notebooks in the same way search does, but that can be a separate issue/ticket since this relies much more on manipulating the score based (which I need to think more on) on the recommended …

Notebook Verification Changes

---

app/views/exception_notifier/_controller.text.erb
app/views/exception_notifier/_environment.text.erb
app/views/exception_notifier/_exception.text.erb
config/environments/development.rb
config/environments/production.rb
docker-compose.yml
docker-dev.sh

- added templates for the controller, environment, and exception sections
- opened necessary ports for the fake-smtp server
- added necessary env vars. for the fake-smtp server and Exception Notification gem
- removed the `data` section as it seems to duplicate in the emails

Add custom templates for the exception emails.

---

app/controllers/notebooks_controller.rb
app/controllers/revisions_controller.rb

This PR normalizes line breaks to ensure consistent behavior in the character counting logic:
Our character counting implementation has a discrepancy between client and server. When users enter line breaks in the form:
- In JavaScript (client-side): Each line break counts as 1 character (`\n`)
- In Ruby (server-side): Each line break counts as 2 characters (`\r\n`)
Currently on `main`, the example below would cause an error even though its exactly 250 characters (the maximum limit for a changelog).
```
Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, 
nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium
```
The backend would complain and …

LF normalization on the changelog

---

app/models/notebook.rb
app/views/application/_notebook_run.slim
app/views/notebooks/_notebook_info_jumbotron.slim

Originally the notebook was checking to see if active exists. Not really a great way of doing it, so this PR aims to make active a method that can be overwritten by extensions. This will make it easier to develop in the future by offering more flexibility. Checking for active notebook was also added to reviews and modifications were made to backend on displaying "Run in Jupyter" button.

Making active an optional notebook method

---

app/helpers/notebooks_helper.rb
app/models/notebook.rb
app/models/review.rb
app/views/notebooks/_notebook_info_jumbotron.slim
app/views/notebooks/_notebook_jumbotron_title.slim
app/views/revisions/show.slim

These changes make it so when a user looks up a specific notebook version/revision, the correct reviews and review status will appear on the page. This DOES NOT change the metrics/non-review related actions and will still show and execute those for the current notebook version (starring, subscribing, health checks, other metrics). We can explore doing that at a later date if wanted but in my opinion it's not worth it.
This PR is unrelated to #1022 but if you have reviewed this you will need to merge `origin/filter-unapproved-notebooks` into your local `fix-revision-view-reviews` to fully test it without error (but DO NOT PUSH/SYNC). To avoid the socket error (that is just a result of not having a fake smtp server linked) comment out `app/controllers/notebooks_controllers.rb:212`.

Showing the proper reviews on a specific notebook version/revision

---

app/views/modals/_new_group.slim

**Issue**
Running a lighthouse accessibility report returned duplicate element IDs; the value of an ARIA ID must be unique to prevent other instances from being overlooked by assistive technologies.
- renamed ` id="newGroupDescription"` to `id="newGroupDialogDescription"` for new group dialog screen reader only paragraph
- None

Edited duplicate Aria IDs

---

app/views/static_pages/home.slim

**Issue**
14. Magnifying glass button within search on homepage just announces 'button'.
In an accessibility audit (linked above) it was noticed that the search button on the homepage (magnifying glass icon) isn't announced correctly by screen readers. 
- Aria label added to the button to enable correct screen reader announcement
- Screen reader will now announce 'Search button' on focus.
**To replicate:**
- On the homepage, with a screen reader active `Tab`to the search button icon
- Expect screen reader to announce 'Search button'

Accessibility - Added aria-label for homepage search button

---

app/assets/stylesheets/styles.scss

**Issue**
10. Long lines in code cells wrap into line number margin.
In an accessibility audit (linked above) it was noticed that the test wrap of code cells could be aligned better for users that view the web page at high zoom levels. This PR aims to solve this with CSS styling.
- CSS styling of code-blocks were edited to move content right and to reposition line numbers absolutely so that they are centered on the left hand side. 
- In an open Jupyter Notebook, text no longer wraps beneath line numbers at 400% zoom; instead they are left aligned and offset to the right of line numbers.
**To replicate:**
- Open any Jupyter Notebook, zoom in to 400% and expect text within code block not to …

Fixed text wrap styling at 400% zoom

---

app/assets/stylesheets/formatters.scss

**Issue**
8. Keywords, comments and logical operators meet WCAG AA for contrast but not AAA
In an accessibility audit (linked above) it was noted that colours within notebook cells meet WCAG AA standards but not AAA. This PR aims to address this so that colours meet triple A.
- CSS styling cell elements changed to nearest suggested colour that meets AAA contrast ratio using dev tools. 
- Colours of cell elements have slight changes.

Changed CSS styling of cells to meet WCAG AAA requirements

---

app/assets/javascripts/gallery.js.erb

**Issue**
This PR aims to partially solve solve some of the 'Keyboard Navigation' issues outlined in the link above. E.g. Enter/Spacebar functionality, specifically the inability to open dialogs with first `Enter`/`Space`key press on a button. Previously pressing `Enter` or `Space` causes a dialog to open and then immediately close again.
- `e.stopPropagation() `added to acessibility key down handler within gallery.js.erb
- Buttons which open a dialog on click will now open on first key press of Enter or Space (e.g. create group/upload buttons)
**To replicate:**
- `Tab` to upload and press `Enter`, expect dialog to open correctly first time
- Repeat for other dialog buttons e.g. 'Create …

Accessibility Keyboard Navigation - Fix opening Dialogs with enter and space key press

---

app/assets/javascripts/gallery.js.erb

**Issue**
https://github.com/nbgallery/nbgallery/issues/980
Keyboard navigation for non-mouse users is difficult when interacting with some input elements.
Final Touches From PR https://github.com/nbgallery/nbgallery/pull/990 for Show Verified Checkbox
- Setting state of input elements within local storage
- Function added to to check and remove state when page is rendered and set focus to previously selected element
**User-facing changes**:
- If user has toggled checkbox/drop-down focus will remain on that element once page loads
**To replicate:**
- Navigate to Advanced Search page
- Tab through to Show Verified Only check box, press Space
- Expect focus to remain on the selected checkbox
- Repeat steps for My Notebooks page and include changing the value in the sort …

keep focus on show verified checkbox after page reload
